server:
  port: 8080

spring:
  application:
    name: hotel_booking_system
  datasource:
    url: jdbc:postgresql://hotel-booking-db.c9cmqoimyxit.us-east-2.rds.amazonaws.com/hotel_booking
    username: postgres
    password: Test123!
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
application:
  security:
    jwt:
      secret-key: d5608c2a97c84dd0c0e0374ab865a131e0305df3f642ff83a03d796d748ac251
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days